---

- name: Assert service(s) to monitor are defined
  assert:
    that: service_exporter_service_list is defined
    msg: "Service(s) to monitor must be defined (service_exporter_service_list)"


- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    service_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in service_exporter_web_listen_address"
